name: Daily Music Chart Collection

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '18 2 * * *'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install Chrome dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libxss1 libasound2 libatk-bridge2.0-0 libgtk-3-0 libgbm-dev
    
    - name: Install dependencies
      run: |
        npm install
        npx puppeteer browsers install chrome
    
    - name: Run chart collection scripts
      run: |
        node apple.js
        node bugs.js
        node flo.js
        node melon.js
    
    - name: Commit changes
      run: |
        git config --global user.email "woogamjaa@gmail.com"
        git config --global user.name "gamja"
        git add apple/apple100_*.json
        git add bugs/bugs100_*.json
        git add flo/flo100_*.json
        git add melon/melon100_*.json
        git diff --quiet && git diff --staged --quiet || git commit -m "차트 데이터 자동 수집 $(date +'%Y-%m-%d')"
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}